approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules
npmAlwaysAuth: true

npmMinimalAgeGate: 0

npmRegistryServer: "https://pkgs.dev.azure.com/DomoreexpGithub/_packaging/github-npm-mirror/npm/registry/
