approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules
npmAlwaysAuth: true

npmMinimalAgeGate: 0

npmRegistryServer: "https://pkgs.dev.azure.com/DomoreexpGithub/Github_Pipelines/_packaging/github-npm-mirror/npm/registry/"
