approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules
npmAlwaysAuth: true

npmMinimalAgeGate: 0

npmRegistryServer: "https://domoreexp.pkgs.visualstudio.com/_packaging/npm-mirror/npm/registry/"
