trigger:
  - "*"

  parameters:
    stages:
      - stage: release
        jobs:
          - job: Release
            variables:
              - group: oss-secrets
            pool:
              name: Azure-Pipelines-1ESPT-ExDShared
              image: ubuntu-latest
              os: linux
            steps:
              - script: |
                  echo "Waiting for 2 seconds..."
                  sleep 2
                  echo "Returning success."
                displayName: Wait and return success
