pr: none
trigger:
  - main
  - apollo-fragment-store-watching

variables:
  - group: InfoSec-SecurityResults
  - name: tags
    value: production,externalfacing
  - name: serviceTreeID
    value: 6F8CD842-E117-412F-BAE4-56A3B6166594
  - name: adoNpmFeedBaseUrl
    value: https://pkgs.dev.azure.com/domoreexp/_apis/packaging/feeds/npm-mirror

jobs:
  - job: compliance
    displayName: Compliance checks
    pool:
      name: 1ES-Teams-Windows-2019-Compliant
    steps:
      - template: ./steps/service-tree.yml
        parameters:
          serviceTreeID: $(serviceTreeID)
      - template: ./steps/compliance-steps.yml

  - job: Release
    variables:
      - group: oss-secrets
    dependsOn: Compliance
    pool: "1ES-Teams-Ubuntu-Latest-Compliant"
    steps:
      - template: ./steps/service-tree.yml
        parameters:
          serviceTreeID: $(serviceTreeID)
      - script: yarn
        displayName: yarn
      - script: |
          yarn ci
        displayName: build and test [test]
      - script: |
          git config user.email "gql-svc@microsoft.com"
          git config user.name "Graphitation Service Account"
          git remote set-url origin https://gql-svc:$(ossGithubPAT)@github.com/microsoft/graphitation.git
        displayName: Configure git for release
      - script: yarn release -y -n $(ossNpmToken) --access public
        displayName: Release
      - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
        displayName: 📒 Generate Manifest
        inputs:
          BuildDropPath: $(System.DefaultWorkingDirectory)
      - task: PublishPipelineArtifact@1
        displayName: 📒 Publish Manifest
        inputs:
          artifactName: SBom-$(System.JobAttempt)
          targetPath: $(System.DefaultWorkingDirectory)/_manifest
      - template: ./steps/pierce-ado-npm-mirror-cache.yml
        parameters:
          adoNpmFeedPat: $(adoNpmFeedPat)
          adoNpmFeedBaseUrl: $(adoNpmFeedBaseUrl)
