import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

export const useStyles = makeStyles({
  root: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  dialogContainer: {
    backgroundColor: tokens.colorNeutralBackground1,
    ...shorthands.borderRadius(tokens.borderRadiusLarge),
    maxWidth: "90%",
    width: "1200px",
    maxHeight: "90vh",
    display: "grid",
    gridTemplateRows: "auto 1fr",
    boxShadow: tokens.shadow64,
    ...shorthands.overflow("hidden"),
  },
  header: {
    display: "grid",
    gridTemplateColumns: "1fr auto",
    alignItems: "start",
    ...shorthands.gap(tokens.spacingHorizontalM),
    ...shorthands.padding(tokens.spacingVerticalL, tokens.spacingHorizontalL),
    ...shorthands.borderBottom(
      tokens.strokeWidthThin,
      "solid",
      tokens.colorNeutralStroke1,
    ),
  },
  headerContent: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap(tokens.spacingVerticalS),
  },
  operationMetadata: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap(tokens.spacingVerticalXXS),
    ...shorthands.padding(tokens.spacingVerticalS, tokens.spacingHorizontalM),
    backgroundColor: tokens.colorNeutralBackground2,
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
  },
  operationVariables: {
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: tokens.fontSizeBase200,
    color: tokens.colorNeutralForeground2,
    wordBreak: "break-all",
  },
  closeButton: {
    minWidth: "auto",
    alignSelf: "start",
  },
  noHistory: {
    ...shorthands.padding(tokens.spacingVerticalXXL),
    textAlign: "center",
    color: tokens.colorNeutralForeground3,
  },
  contentContainer: {
    display: "grid",
    gridTemplateColumns: "280px 1fr",
    ...shorthands.overflow("hidden"),
    height: "100%",
  },
  timeline: {
    ...shorthands.borderRight(
      tokens.strokeWidthThin,
      "solid",
      tokens.colorNeutralStroke1,
    ),
    display: "grid",
    gridTemplateRows: "auto 1fr",
    ...shorthands.overflow("hidden"),
  },
  sectionTitle: {
    ...shorthands.padding(tokens.spacingVerticalM, tokens.spacingHorizontalM),
    ...shorthands.borderBottom(
      tokens.strokeWidthThin,
      "solid",
      tokens.colorNeutralStroke1,
    ),
  },
  timelineList: {
    overflowY: "auto",
    ...shorthands.padding(tokens.spacingVerticalS),
  },
  timelineItem: {
    ...shorthands.padding(tokens.spacingVerticalS, tokens.spacingHorizontalM),
    ...shorthands.margin(tokens.spacingVerticalXS, 0),
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap(tokens.spacingVerticalXXS),
    ...shorthands.borderLeft("3px", "solid", "transparent"),
    "&:hover": {
      backgroundColor: tokens.colorNeutralBackground1Hover,
      ...shorthands.borderLeft("3px", "solid", tokens.colorNeutralStroke1Hover),
    },
  },
  timelineItemActive: {
    backgroundColor: tokens.colorBrandBackground2,
    ...shorthands.borderLeft("3px", "solid", tokens.colorBrandStroke1),
    "&:hover": {
      backgroundColor: tokens.colorBrandBackground2Hover,
      ...shorthands.borderLeft("3px", "solid", tokens.colorBrandStroke1),
    },
  },
  timelineItemIncomplete: {
    backgroundColor: "rgba(255, 200, 100, 0.15)",
  },
  timelineItemContent: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap(tokens.spacingVerticalXXS),
  },
  timelineItemTime: {
    color: tokens.colorNeutralForeground2,
    fontSize: tokens.fontSizeBase200,
    fontFamily: tokens.fontFamilyMonospace,
  },
  operationName: {
    color: tokens.colorBrandForeground1,
    fontSize: tokens.fontSizeBase200,
    fontFamily: tokens.fontFamilyMonospace,
    fontWeight: tokens.fontWeightSemibold,
  },
  missingFieldsTag: {
    color: tokens.colorPaletteYellowForeground1,
    fontSize: tokens.fontSizeBase100,
    fontWeight: tokens.fontWeightSemibold,
    marginTop: tokens.spacingVerticalXXS,
  },
  changeCountTag: {
    fontSize: tokens.fontSizeBase100,
    color: tokens.colorNeutralForeground3,
    marginTop: tokens.spacingVerticalXXS,
  },
  optimisticTag: {
    fontSize: tokens.fontSizeBase100,
    color: tokens.colorBrandForeground1,
    fontWeight: tokens.fontWeightSemibold,
    marginTop: tokens.spacingVerticalXXS,
    ...shorthands.padding(
      tokens.spacingVerticalXXS,
      tokens.spacingHorizontalXS,
    ),
    backgroundColor: "rgba(0, 120, 212, 0.15)",
    ...shorthands.borderRadius(tokens.borderRadiusSmall),
  },
  timelineItemOptimistic: {
    backgroundColor: "rgba(0, 120, 212, 0.08)",
    ...shorthands.borderLeft("3px", "solid", tokens.colorBrandStroke1),
  },
  optimisticBadge: {
    display: "inline-flex",
    alignItems: "center",
    ...shorthands.padding(
      tokens.spacingVerticalXXS,
      tokens.spacingHorizontalXS,
    ),
    backgroundColor: "rgba(0, 120, 212, 0.15)",
    color: tokens.colorBrandForeground1,
    ...shorthands.borderRadius(tokens.borderRadiusSmall),
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightSemibold,
    marginLeft: tokens.spacingHorizontalS,
  },
  detailsPanel: {
    overflowY: "auto",
    ...shorthands.padding(tokens.spacingVerticalM, tokens.spacingHorizontalL),
  },
  emptyState: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
    color: tokens.colorNeutralForeground3,
  },
  detailsContent: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap(tokens.spacingVerticalM),
  },
  operationHeader: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap(tokens.spacingVerticalS),
    ...shorthands.padding(tokens.spacingVerticalM, tokens.spacingHorizontalM),
    backgroundColor: tokens.colorNeutralBackground2,
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
  },
  operationTitle: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap(tokens.spacingVerticalXXS),
  },
  operationTimestamp: {
    color: tokens.colorNeutralForeground3,
    fontFamily: tokens.fontFamilyMonospace,
  },
  operationVariablesBox: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap(tokens.spacingVerticalXXS),
    marginTop: tokens.spacingVerticalXS,
  },
  variablesCode: {
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: tokens.fontSizeBase100,
    ...shorthands.padding(tokens.spacingVerticalXS, tokens.spacingHorizontalS),
    backgroundColor: tokens.colorNeutralBackground1,
    ...shorthands.borderRadius(tokens.borderRadiusSmall),
    ...shorthands.overflow("auto"),
    maxHeight: "200px",
  },
  detailSection: {
    ...shorthands.padding(tokens.spacingVerticalM, 0),
    ...shorthands.borderBottom(
      tokens.strokeWidthThin,
      "solid",
      tokens.colorNeutralStroke1,
    ),
  },
  timestamp: {
    display: "block",
    marginBottom: tokens.spacingVerticalS,
  },
  operationInfo: {
    color: tokens.colorNeutralForeground3,
    fontFamily: tokens.fontFamilyMonospace,
  },
  variablesSection: {
    marginTop: tokens.spacingVerticalS,
    ...shorthands.padding(tokens.spacingVerticalS),
    backgroundColor: tokens.colorNeutralBackground2,
    ...shorthands.borderRadius(tokens.borderRadiusSmall),
  },
  section: {
    display: "flex",
    flexDirection: "column",
  },
  sectionHeader: {
    justifyContent: "flex-start",
    ...shorthands.padding(tokens.spacingVerticalS, 0),
    width: "100%",
    ...shorthands.gap(tokens.spacingHorizontalS),
  },
  chevron: {
    ...shorthands.transition("transform", "0.2s"),
  },
  chevronExpanded: {
    transform: "rotate(90deg)",
  },
  sectionContent: {
    ...shorthands.padding(tokens.spacingVerticalS, 0),
  },
  changesGroup: {
    marginBottom: tokens.spacingVerticalM,
  },
  changesLabel: {
    display: "block",
    marginBottom: tokens.spacingVerticalS,
    color: tokens.colorBrandForeground1,
    fontSize: tokens.fontSizeBase300,
    ...shorthands.padding(tokens.spacingVerticalS, 0),
    ...shorthands.borderBottom(
      tokens.strokeWidthThin,
      "solid",
      tokens.colorNeutralStroke1,
    ),
  },
  // New row-based change item design
  changeItemRow: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.margin(tokens.spacingVerticalXS, 0),
    ...shorthands.padding(tokens.spacingVerticalXS, 0),
    ...shorthands.borderBottom(
      tokens.strokeWidthThin,
      "solid",
      tokens.colorNeutralStroke2,
    ),
  },
  changeItemRowHeader: {
    display: "flex",
    alignItems: "center",
    ...shorthands.gap(tokens.spacingHorizontalS),
    ...shorthands.padding(tokens.spacingVerticalXS, 0),
    cursor: "pointer",
    "&:hover": {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  changeRowChevron: {
    fontSize: "16px",
    color: tokens.colorNeutralForeground3,
    ...shorthands.transition("transform", "0.2s"),
    flexShrink: 0,
  },
  changeFieldName: {
    fontFamily: tokens.fontFamilyMonospace,
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorNeutralForeground1,
    minWidth: "120px",
  },
  changeTypeLabel: {
    color: tokens.colorNeutralForeground3,
    fontSize: tokens.fontSizeBase100,
    ...shorthands.padding(
      tokens.spacingVerticalXXS,
      tokens.spacingHorizontalXS,
    ),
    backgroundColor: tokens.colorNeutralBackground3,
    ...shorthands.borderRadius(tokens.borderRadiusSmall),
    flexShrink: 0,
  },
  changePreviewText: {
    color: tokens.colorNeutralForeground2,
    fontFamily: tokens.fontFamilyMonospace,
    flexGrow: 1,
  },
  changeExpandedContent: {
    ...shorthands.padding(
      tokens.spacingVerticalS,
      0,
      tokens.spacingVerticalS,
      "24px",
    ),
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap(tokens.spacingVerticalXS),
  },
  valueComparisonInline: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    ...shorthands.gap(tokens.spacingHorizontalM),
  },
  valueLabel: {
    color: tokens.colorNeutralForeground3,
    marginBottom: tokens.spacingVerticalXXS,
  },
  valueCodeInline: {
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: tokens.fontSizeBase100,
    ...shorthands.padding(tokens.spacingVerticalXS, tokens.spacingHorizontalS),
    backgroundColor: tokens.colorNeutralBackground2,
    ...shorthands.borderRadius(tokens.borderRadiusSmall),
    ...shorthands.overflow("auto"),
    maxHeight: "150px",
  },
  arrayWarningInfo: {
    ...shorthands.padding(tokens.spacingVerticalXS, tokens.spacingHorizontalS),
    backgroundColor: "rgba(255, 200, 100, 0.1)",
    ...shorthands.borderRadius(tokens.borderRadiusSmall),
    ...shorthands.borderLeft("2px", "solid", tokens.colorPaletteYellowBorder2),
  },
  arrayItemRow: {
    ...shorthands.padding(tokens.spacingVerticalXS, tokens.spacingHorizontalS),
    backgroundColor: tokens.colorNeutralBackground2,
    ...shorthands.borderRadius(tokens.borderRadiusSmall),
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap(tokens.spacingVerticalXXS),
  },
  arrayItemRowIncomplete: {
    backgroundColor: "rgba(255, 200, 100, 0.2)",
    ...shorthands.borderLeft("3px", "solid", tokens.colorPaletteYellowBorder2),
  },
  itemMissingFields: {
    fontSize: tokens.fontSizeBase100,
    color: tokens.colorPaletteYellowForeground1,
    marginTop: tokens.spacingVerticalXXS,
  },
  missingFieldName: {
    fontFamily: tokens.fontFamilyMonospace,
  },
  warningBadge: {
    color: tokens.colorPaletteYellowForeground1,
    fontSize: tokens.fontSizeBase100,
    ...shorthands.padding(
      tokens.spacingVerticalXXS,
      tokens.spacingHorizontalXS,
    ),
    backgroundColor: "rgba(255, 200, 100, 0.15)",
    ...shorthands.borderRadius(tokens.borderRadiusSmall),
  },
  inlineCode: {
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: tokens.fontSizeBase200,
    ...shorthands.padding(tokens.spacingVerticalS),
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    marginTop: tokens.spacingVerticalXS,
  },
  codeBlock: {
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: tokens.fontSizeBase200,
    ...shorthands.padding(tokens.spacingVerticalS, tokens.spacingHorizontalM),
    backgroundColor: tokens.colorNeutralBackground3,
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    ...shorthands.overflow("auto"),
    maxHeight: "500px",
    ...shorthands.border(
      tokens.strokeWidthThin,
      "solid",
      tokens.colorNeutralStroke2,
    ),
  },
  noChanges: {
    color: tokens.colorNeutralForeground3,
    fontStyle: "italic",
    fontSize: tokens.fontSizeBase200,
    ...shorthands.padding(tokens.spacingVerticalM),
  },
  missingSectionTitle: {
    color: tokens.colorPaletteYellowForeground1,
    display: "flex",
    alignItems: "center",
    ...shorthands.gap(tokens.spacingHorizontalXS),
  },
  missingFieldsItem: {
    ...shorthands.padding(tokens.spacingVerticalM, tokens.spacingHorizontalM),
    ...shorthands.margin(tokens.spacingVerticalS, 0),
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    backgroundColor: "rgba(255, 200, 100, 0.1)",
    ...shorthands.border(
      tokens.strokeWidthThin,
      "solid",
      "rgba(255, 200, 100, 0.3)",
    ),
  },
  missingFieldsList: {
    display: "flex",
    flexWrap: "wrap",
    ...shorthands.gap(tokens.spacingHorizontalS),
    marginTop: tokens.spacingVerticalS,
  },
  missingFieldChip: {
    ...shorthands.padding(tokens.spacingVerticalXS, tokens.spacingHorizontalS),
    backgroundColor: tokens.colorPaletteYellowBackground1,
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    ...shorthands.border(
      tokens.strokeWidthThin,
      "solid",
      tokens.colorPaletteYellowBorder2,
    ),
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: tokens.fontSizeBase200,
  },
  // Diff viewer styles
  diffViewerContainer: {
    marginTop: tokens.spacingVerticalM,
    ...shorthands.border(
      tokens.strokeWidthThin,
      "solid",
      tokens.colorNeutralStroke2,
    ),
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    ...shorthands.overflow("hidden"),
  },
  diffViewerHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    ...shorthands.padding(tokens.spacingVerticalS, tokens.spacingHorizontalM),
    backgroundColor: tokens.colorNeutralBackground3,
    ...shorthands.borderBottom(
      tokens.strokeWidthThin,
      "solid",
      tokens.colorNeutralStroke2,
    ),
  },
  diffViewerContent: {
    maxHeight: "600px",
    overflowY: "auto",
    backgroundColor: tokens.colorNeutralBackground1,
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: tokens.fontSizeBase200,
  },
  diffLine: {
    display: "flex",
    ...shorthands.padding(tokens.spacingVerticalXS, tokens.spacingHorizontalM),
    whiteSpace: "pre",
    fontFamily: "inherit",
    fontSize: "inherit",
  },
  diffLineNumber: {
    minWidth: "50px",
    textAlign: "right",
    marginRight: tokens.spacingHorizontalM,
    color: tokens.colorNeutralForeground3,
    userSelect: "none",
  },
  diffLineContent: {
    ...shorthands.flex(1),
    whiteSpace: "pre-wrap",
    wordBreak: "break-all",
  },
  diffLineAdded: {
    backgroundColor: "rgba(46, 160, 67, 0.15)",
    ...shorthands.borderLeft("3px", "solid", tokens.colorPaletteGreenBorder2),
  },
  diffLineDeleted: {
    backgroundColor: "rgba(229, 83, 75, 0.15)",
    ...shorthands.borderLeft("3px", "solid", tokens.colorPaletteRedBorder2),
  },
  diffLineModified: {
    backgroundColor: "rgba(245, 159, 0, 0.15)",
    ...shorthands.borderLeft("3px", "solid", tokens.colorPaletteYellowBorder2),
  },
  diffLineUnchanged: {
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground2,
  },
  diffStats: {
    display: "flex",
    ...shorthands.gap(tokens.spacingHorizontalL),
    fontSize: tokens.fontSizeBase300,
    fontWeight: tokens.fontWeightSemibold,
  },
  diffStatItem: {
    display: "flex",
    alignItems: "center",
    ...shorthands.gap(tokens.spacingHorizontalXS),
  },
  diffStatAdded: {
    color: tokens.colorPaletteGreenForeground1,
  },
  diffStatDeleted: {
    color: tokens.colorPaletteRedForeground1,
  },
  diffStatModified: {
    color: tokens.colorPaletteYellowForeground1,
  },
  diffToggle: {
    marginBottom: tokens.spacingVerticalS,
    display: "flex",
    alignItems: "center",
  },
});
