// THIS FILE IS GENERATED BY graphql-codegen. DO NOT MODIFY!
// RUN `yarn generate:interfaces` from the package root to update it
// See <PACKAGE_ROOT>/codegen.yml for details
/* eslint-disable */
// @ts-nocheck

import * as Types from '../src/__generated__/types.js';

import { DocumentNode } from "graphql";
export type TodoListQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type TodoListQuery = { readonly allTodos: ReadonlyArray<{ readonly __typename: 'Todo', readonly id: string, readonly text: string, readonly isCompleted: boolean }> };

export type TodoFragment = { readonly __typename: 'Todo', readonly id: string, readonly text: string, readonly isCompleted: boolean };

export type TodoCompletedFragment = { readonly __typename: 'Todo', readonly isCompleted: boolean };

export const TodoListQueryDocument: DocumentNode = (function(){
var v0 = {
  "kind": "Field",
  "name": {
    "kind": "Name",
    "value": "id"
  },
  "arguments": ([]/*: any*/),
  "directives": ([]/*: any*/)
},
v1 = {
  "kind": "Name",
  "value": "TodoFragment"
},
v2 = {
  "kind": "NamedType",
  "name": {
    "kind": "Name",
    "value": "Todo"
  }
},
v3 = {
  "kind": "Name",
  "value": "TodoCompletedFragment"
},
v4 = [
  {
    "alias": null,
    "args": null,
    "concreteType": "Todo",
    "kind": "LinkedField",
    "name": "allTodos",
    "plural": true,
    "selections": [
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "id",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "text",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "isCompleted",
        "storageKey": null
      }
    ],
    "storageKey": null
  }
];
return {
  "kind": "Document",
  "definitions": [
    {
      "kind": "OperationDefinition",
      "operation": "query",
      "name": {
        "kind": "Name",
        "value": "TodoListQuery"
      },
      "variableDefinitions": [],
      "directives": [],
      "selectionSet": {
        "kind": "SelectionSet",
        "selections": [
          {
            "kind": "Field",
            "name": {
              "kind": "Name",
              "value": "allTodos"
            },
            "arguments": [],
            "directives": [],
            "selectionSet": {
              "kind": "SelectionSet",
              "selections": [
                (v0/*: any*/),
                {
                  "kind": "FragmentSpread",
                  "name": (v1/*: any*/),
                  "directives": []
                }
              ]
            }
          }
        ]
      }
    },
    {
      "kind": "FragmentDefinition",
      "name": (v1/*: any*/),
      "typeCondition": (v2/*: any*/),
      "directives": [],
      "selectionSet": {
        "kind": "SelectionSet",
        "selections": [
          (v0/*: any*/),
          {
            "kind": "Field",
            "name": {
              "kind": "Name",
              "value": "text"
            },
            "arguments": [],
            "directives": []
          },
          {
            "kind": "FragmentSpread",
            "name": (v3/*: any*/),
            "directives": []
          }
        ]
      }
    },
    {
      "kind": "FragmentDefinition",
      "name": (v3/*: any*/),
      "typeCondition": (v2/*: any*/),
      "directives": [],
      "selectionSet": {
        "kind": "SelectionSet",
        "selections": [
          {
            "kind": "Field",
            "name": {
              "kind": "Name",
              "value": "isCompleted"
            },
            "arguments": [],
            "directives": []
          }
        ]
      }
    }
  ],
  "__relay": {
    "fragment": {
      "argumentDefinitions": [],
      "kind": "Fragment",
      "metadata": null,
      "name": "TodoListQuery",
      "selections": (v4/*: any*/),
      "type": "Query",
      "abstractKey": null
    },
    "kind": "Request",
    "operation": {
      "argumentDefinitions": [],
      "kind": "Operation",
      "name": "TodoListQuery",
      "selections": (v4/*: any*/)
    },
    "params": {
      "cacheID": "d41d8cd98f00b204e9800998ecf8427e",
      "metadata": {},
      "name": "TodoListQuery",
      "operationKind": "query",
      "text": ""
    }
  }
};
})();
export const TodoFragmentDocument: DocumentNode = {
  "kind": "Document",
  "definitions": [
    {
      "kind": "FragmentDefinition",
      "name": {
        "kind": "Name",
        "value": "TodoFragment"
      },
      "typeCondition": {
        "kind": "NamedType",
        "name": {
          "kind": "Name",
          "value": "Todo"
        }
      },
      "directives": [],
      "selectionSet": {
        "kind": "SelectionSet",
        "selections": [
          {
            "kind": "Field",
            "name": {
              "kind": "Name",
              "value": "id"
            },
            "arguments": [],
            "directives": []
          },
          {
            "kind": "Field",
            "name": {
              "kind": "Name",
              "value": "text"
            },
            "arguments": [],
            "directives": []
          },
          {
            "kind": "Field",
            "name": {
              "kind": "Name",
              "value": "isCompleted"
            },
            "arguments": [],
            "directives": []
          }
        ]
      }
    }
  ],
  "__relay": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "TodoFragment",
    "selections": [
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "id",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "text",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "isCompleted",
        "storageKey": null
      }
    ],
    "type": "Todo",
    "abstractKey": null
  }
};
export const TodoCompletedFragmentDocument: DocumentNode = {
  "kind": "Document",
  "definitions": [
    {
      "kind": "FragmentDefinition",
      "name": {
        "kind": "Name",
        "value": "TodoCompletedFragment"
      },
      "typeCondition": {
        "kind": "NamedType",
        "name": {
          "kind": "Name",
          "value": "Todo"
        }
      },
      "directives": [],
      "selectionSet": {
        "kind": "SelectionSet",
        "selections": [
          {
            "kind": "Field",
            "name": {
              "kind": "Name",
              "value": "isCompleted"
            },
            "arguments": [],
            "directives": []
          }
        ]
      }
    }
  ],
  "__relay": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "TodoCompletedFragment",
    "selections": [
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "isCompleted",
        "storageKey": null
      }
    ],
    "type": "Todo",
    "abstractKey": null
  }
};