// THIS FILE IS GENERATED BY graphql-codegen. DO NOT MODIFY!
// RUN `yarn generate:interfaces` from the package root to update it
// See <PACKAGE_ROOT>/codegen.yml for details
/* eslint-disable */
// @ts-nocheck

import * as Types from '../src/__generated__/types.js';

import { DocumentNode } from "graphql"
export type TodoUpdatesSubscriptionSubscriptionVariables = Types.Exact<{
  limit: Types.Scalars['Int'];
}>;


export type TodoUpdatesSubscriptionSubscription = { __typename?: 'Subscription', emitTodos?: { __typename?: 'Todo', id: string, text: string, isCompleted: boolean } | null };

export type TodoFragmentFragment = { __typename?: 'Todo', id: string, text: string, isCompleted: boolean };

export const TodoUpdatesSubscriptionDocument: DocumentNode = (function(){
var v0 = {
  "kind": "Name",
  "value": "limit"
},
v1 = {
  "kind": "Variable",
  "name": (v0/*: any*/)
},
v2 = {
  "kind": "NonNullType",
  "type": {
    "kind": "NamedType",
    "name": {
      "kind": "Name",
      "value": "Int"
    }
  }
},
v3 = [
  {
    "defaultValue": null,
    "kind": "LocalArgument",
    "name": "limit"
  }
],
v4 = [
  {
    "kind": "Variable",
    "name": "limit",
    "variableName": "limit"
  }
],
v5 = {
  "alias": null,
  "args": null,
  "kind": "ScalarField",
  "name": "id",
  "storageKey": null
};
return {
  "kind": "Document",
  "definitions": [
    {
      "kind": "OperationDefinition",
      "operation": "subscription",
      "name": {
        "kind": "Name",
        "value": "TodoUpdatesSubscription"
      },
      "variableDefinitions": [
        {
          "kind": "VariableDefinition",
          "variable": (v1/*: any*/),
          "type": (v2/*: any*/),
          "directives": []
        }
      ],
      "directives": [],
      "selectionSet": {
        "kind": "SelectionSet",
        "selections": [
          {
            "kind": "Field",
            "name": {
              "kind": "Name",
              "value": "emitTodos"
            },
            "arguments": [
              {
                "kind": "Argument",
                "name": (v0/*: any*/),
                "value": (v1/*: any*/),
                "__type": (v2/*: any*/)
              }
            ],
            "directives": [],
            "selectionSet": {
              "kind": "SelectionSet",
              "selections": [
                {
                  "kind": "Field",
                  "name": {
                    "kind": "Name",
                    "value": "id"
                  },
                  "arguments": [],
                  "directives": [],
                  "__type": {
                    "kind": "NonNullType",
                    "type": {
                      "kind": "NamedType",
                      "name": {
                        "kind": "Name",
                        "value": "ID"
                      }
                    }
                  }
                },
                {
                  "kind": "FragmentSpread",
                  "name": {
                    "kind": "Name",
                    "value": "TodoFragment"
                  },
                  "directives": []
                }
              ]
            },
            "__type": {
              "kind": "NamedType",
              "name": {
                "kind": "Name",
                "value": "Todo"
              }
            }
          }
        ]
      }
    }
  ],
  "__relay": {
    "fragment": {
      "argumentDefinitions": (v3/*: any*/),
      "kind": "Fragment",
      "metadata": null,
      "name": "TodoUpdatesSubscription",
      "selections": [
        {
          "alias": null,
          "args": (v4/*: any*/),
          "concreteType": "Todo",
          "kind": "LinkedField",
          "name": "emitTodos",
          "plural": false,
          "selections": [
            (v5/*: any*/),
            {
              "args": null,
              "kind": "FragmentSpread",
              "name": "TodoFragment"
            }
          ],
          "storageKey": null
        }
      ],
      "type": "Subscription",
      "abstractKey": null
    },
    "kind": "Request",
    "operation": {
      "argumentDefinitions": (v3/*: any*/),
      "kind": "Operation",
      "name": "TodoUpdatesSubscription",
      "selections": [
        {
          "alias": null,
          "args": (v4/*: any*/),
          "concreteType": "Todo",
          "kind": "LinkedField",
          "name": "emitTodos",
          "plural": false,
          "selections": [
            (v5/*: any*/),
            {
              "alias": null,
              "args": null,
              "kind": "ScalarField",
              "name": "text",
              "storageKey": null
            },
            {
              "alias": null,
              "args": null,
              "kind": "ScalarField",
              "name": "isCompleted",
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ]
    },
    "params": {
      "cacheID": "d41d8cd98f00b204e9800998ecf8427e",
      "metadata": {},
      "name": "TodoUpdatesSubscription",
      "operationKind": "subscription",
      "text": ""
    }
  }
};
})();
export const TodoFragmentDocument: DocumentNode = {
  "kind": "Document",
  "definitions": [
    {
      "kind": "FragmentDefinition",
      "name": {
        "kind": "Name",
        "value": "TodoFragment"
      },
      "typeCondition": {
        "kind": "NamedType",
        "name": {
          "kind": "Name",
          "value": "Todo"
        }
      },
      "directives": [],
      "selectionSet": {
        "kind": "SelectionSet",
        "selections": [
          {
            "kind": "Field",
            "name": {
              "kind": "Name",
              "value": "id"
            },
            "arguments": [],
            "directives": [],
            "__type": {
              "kind": "NonNullType",
              "type": {
                "kind": "NamedType",
                "name": {
                  "kind": "Name",
                  "value": "ID"
                }
              }
            }
          },
          {
            "kind": "Field",
            "name": {
              "kind": "Name",
              "value": "text"
            },
            "arguments": [],
            "directives": [],
            "__type": {
              "kind": "NonNullType",
              "type": {
                "kind": "NamedType",
                "name": {
                  "kind": "Name",
                  "value": "String"
                }
              }
            }
          },
          {
            "kind": "Field",
            "name": {
              "kind": "Name",
              "value": "isCompleted"
            },
            "arguments": [],
            "directives": [],
            "__type": {
              "kind": "NonNullType",
              "type": {
                "kind": "NamedType",
                "name": {
                  "kind": "Name",
                  "value": "Boolean"
                }
              }
            }
          }
        ]
      }
    }
  ],
  "__relay": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "TodoFragment",
    "selections": [
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "id",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "text",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "isCompleted",
        "storageKey": null
      }
    ],
    "type": "Todo",
    "abstractKey": null
  }
};