// THIS FILE IS GENERATED BY graphql-codegen. DO NOT MODIFY!
// RUN `yarn generate:interfaces` from the package root to update it
// See <PACKAGE_ROOT>/codegen.yml for details
/* eslint-disable */
// @ts-nocheck

import * as Types from '../src/__generated__/types.js';

import { DocumentNode } from "graphql";
export type TodoCreatedSubscriptionVariables = Types.Exact<{ [key: string]: never; }>;


export type TodoCreatedSubscription = { readonly todoCreated: { readonly __typename: 'Todo', readonly id: string, readonly text: string, readonly isCompleted: boolean } | null };

export const TodoCreatedSubscriptionDocument: DocumentNode = (function(){
var v0 = [
  {
    "alias": null,
    "args": null,
    "concreteType": "Todo",
    "kind": "LinkedField",
    "name": "todoCreated",
    "plural": false,
    "selections": [
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "__typename",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "id",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "text",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "isCompleted",
        "storageKey": null
      }
    ],
    "storageKey": null
  }
];
return {
  "kind": "Document",
  "definitions": [
    {
      "kind": "OperationDefinition",
      "operation": "subscription",
      "name": {
        "kind": "Name",
        "value": "TodoCreatedSubscription"
      },
      "variableDefinitions": [],
      "directives": [],
      "selectionSet": {
        "kind": "SelectionSet",
        "selections": [
          {
            "kind": "Field",
            "name": {
              "kind": "Name",
              "value": "todoCreated"
            },
            "arguments": [],
            "directives": [],
            "selectionSet": {
              "kind": "SelectionSet",
              "selections": [
                {
                  "kind": "Field",
                  "name": {
                    "kind": "Name",
                    "value": "__typename"
                  },
                  "arguments": [],
                  "directives": []
                },
                {
                  "kind": "Field",
                  "name": {
                    "kind": "Name",
                    "value": "id"
                  },
                  "arguments": [],
                  "directives": []
                },
                {
                  "kind": "Field",
                  "name": {
                    "kind": "Name",
                    "value": "text"
                  },
                  "arguments": [],
                  "directives": []
                },
                {
                  "kind": "Field",
                  "name": {
                    "kind": "Name",
                    "value": "isCompleted"
                  },
                  "arguments": [],
                  "directives": []
                }
              ]
            }
          }
        ]
      }
    }
  ],
  "__relay": {
    "fragment": {
      "argumentDefinitions": [],
      "kind": "Fragment",
      "metadata": null,
      "name": "TodoCreatedSubscription",
      "selections": (v0/*: any*/),
      "type": "Subscription",
      "abstractKey": null
    },
    "kind": "Request",
    "operation": {
      "argumentDefinitions": [],
      "kind": "Operation",
      "name": "TodoCreatedSubscription",
      "selections": (v0/*: any*/)
    },
    "params": {
      "cacheID": "d41d8cd98f00b204e9800998ecf8427e",
      "metadata": {},
      "name": "TodoCreatedSubscription",
      "operationKind": "subscription",
      "text": ""
    }
  }
};
})();